---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.namePrefix }}-data
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.prometheus.disk.size }}
