---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.namePrefix }}-prometheus-config
  namespace: {{ .Values.namespace }}
data:
  config.yml: |-
    global:
      scrape_interval: 30s

    # Scrape config for cluster components.
    scrape_configs:
      - job_name: prometheus
        static_configs:
          - targets: ['cost-attribution-mk-agent:9101']
